### ISSUE TITLE
Where is Config.h file

### ISSUE THREAD

**Issue by AdaBill** [lukecyca/esp-sous-vide#1]
I tried to compile this and it complained about cannot find "Config.h" file  Why have this as a seperate file, why not just include in main?

**Comment by lukecyca** [comment]
Thanks for checking out this repo!

`config.h` contains all credentials and user-specific stuff. It's a separate file so that it doesn't accidentally get committed to the repo, and so that changes to the main file reflect actual changes to the software (not the configuration).

At the top of the main file, there is a comment showing the `#define`s that need to be located in `config.h`.

**Comment by AdaBill** [comment]
Thanks for the quick response.  It would be helpful if you mentioned this in the sketch.  I wasn't sure if i was missing the file because I wasn't sure what else it was supposed to contain.  Having a seperate file does make sense.
Thanks for the extra tip.
AdaBill
